### ISSUE TITLE
Template docs are missing

### ISSUE THREAD

**Issue by geomorillo** [geomorillo/prestomvc#22]
What? i forgot yet another doc...

**Comment by danielnavram** [comment]
My porpouse, you can analize...

[Templates.MD.zip](https://github.com/geomorillo/prestomvc/files/1085982/Templates.MD.zip)

Regards

**Comment by geomorillo** [comment]
Looks ok with some minor adjustments thanks

**Comment by geomorillo** [comment]
listo
