### ISSUE TITLE
Have to create always header.php or footer.php files

### ISSUE THREAD

**Issue by danielnavram** [geomorillo/prestomvc#25]
Validate this point....

Maybe, we just need to create the file that we need and don't waste the time to creating empty files that maybe never will be use.

**Comment by geomorillo** [comment]
No se necesita crear nada para esto tienes 2 alternativas
solo le pones al template cualquier nombre que no exista en el directorio templates `$this->view->useTemplate("vacio")->render("mivista"); `
ya que el template vacio no existe en el dir "templates" entonces no usa ningun template

pero en vez de eso puedes usar un partial ya que un partial es una vista sin template
`$this->view->partial("mivista");`

**Comment by geomorillo** [comment]
Pienso que como hay alternativas entonces no es tan necesario.
